# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import adminlog
import studentlog
import collegelog
import studentreg
check = True

class Ui_Form(object):
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(729, 549)
        self.hwidget = QtWidgets.QWidget(Form)
        self.hwidget.setGeometry(QtCore.QRect(20, 20, 631, 491))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.hwidget.setFont(font)
        self.hwidget.setStyleSheet("QPushButton#hadmin{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#hadmin:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"QPushButton#hadmin:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#hstudent{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#hstudent:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"QPushButton#hstudent:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#hcollege{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#hcollege:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"QPushButton#hcollege:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}")
        self.hwidget.setObjectName("hwidget")
        self.hlabel = QtWidgets.QLabel(self.hwidget)
        self.hlabel.setGeometry(QtCore.QRect(69, 40, 531, 421))
        self.hlabel.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius:50px")
        self.hlabel.setText("")
        self.hlabel.setObjectName("hlabel")
        self.hlabel_2 = QtWidgets.QLabel(self.hwidget)
        self.hlabel_2.setGeometry(QtCore.QRect(49, 25, 211, 71))
        self.hlabel_2.setStyleSheet("border-top-left-radius:50px;\n"
"background-color:rgba(0,0,0,80);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));")
        self.hlabel_2.setText("")
        self.hlabel_2.setObjectName("hlabel_2")
        self.hlabel_3 = QtWidgets.QLabel(self.hwidget)
        self.hlabel_3.setGeometry(QtCore.QRect(290, 320, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.hlabel_3.setFont(font)
        self.hlabel_3.setStyleSheet("color:rgba(0,0,0,200);")
        self.hlabel_3.setObjectName("hlabel_3")
        self.hadmin = QtWidgets.QPushButton(self.hwidget)
        self.hadmin.setGeometry(QtCore.QRect(150, 360, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.hadmin.setFont(font)
        self.hadmin.setObjectName("hadmin")
        self.hlabel_5 = QtWidgets.QLabel(self.hwidget)
        self.hlabel_5.setGeometry(QtCore.QRect(80, 40, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.hlabel_5.setFont(font)
        self.hlabel_5.setStyleSheet("color:rgba(255,255,255,220);")
        self.hlabel_5.setObjectName("hlabel_5")
        self.hlabel_6 = QtWidgets.QLabel(self.hwidget)
        self.hlabel_6.setGeometry(QtCore.QRect(270, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.hlabel_6.setFont(font)
        self.hlabel_6.setStyleSheet("color:rgba(0,0,0,200);")
        self.hlabel_6.setObjectName("hlabel_6")
        self.hstudent = QtWidgets.QPushButton(self.hwidget)
        self.hstudent.setGeometry(QtCore.QRect(300, 360, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.hstudent.setFont(font)
        self.hstudent.setObjectName("hstudent")
        self.hcollege = QtWidgets.QPushButton(self.hwidget)
        self.hcollege.setGeometry(QtCore.QRect(450, 360, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.hcollege.setFont(font)
        self.hcollege.setObjectName("hcollege")
        self.htextBrowser = QtWidgets.QTextBrowser(self.hwidget)
        self.htextBrowser.setGeometry(QtCore.QRect(80, 100, 511, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.htextBrowser.setFont(font)
        self.htextBrowser.setStyleSheet("color:rgba(255,255,255,220);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;")
        self.htextBrowser.setObjectName("htextBrowser")
        self.hstudent.clicked.connect(self.passage3)
        self.hadmin.clicked.connect(self.passage2)
        self.hcollege.clicked.connect(self.passage4)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hlabel_3.setText(_translate("Form", "Log In As?"))
        self.hadmin.setText(_translate("Form", "Admin"))
        self.hlabel_5.setText(_translate("Form", "Entrée-in"))
        self.hlabel_6.setText(_translate("Form", "Home"))
        self.hstudent.setText(_translate("Form", "Student"))
        self.hcollege.setText(_translate("Form", "College"))
        self.htextBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
" \n\n\n\n\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Entrée-in:Inspired from a French word, our portal aims to create an inclusive and smooth admission process for the candidates.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Our goal of \'Entrée-in\' is to automate all of the participating academic institute’s admission structure and its related operation and functionality. The objective of this initiative is to provide complete support to the administration and admission seeking candidates by providing a faster and transparent way of keeping records and using them for reference and further proceedings.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        global check
        check = True
        if(check):
                global x
                x = Form
                check = False

    def collegelog(self,x):                            
        self.window4 = QtWidgets.QMainWindow()
        self.ui = collegelog.Ui_Form()
        self.ui.setupUi(self.window4)
        self.window4.show()
        x.close()

    def passage4(self):
        self.collegelog(x)
        
    def studentlog(self,x):                            
        self.window3 = QtWidgets.QMainWindow()
        self.ui = studentlog.Ui_Form()
        self.ui.setupUi(self.window3)
        self.window3.show()
        x.close()

    def passage3(self):
        self.studentlog(x)
        
    def adminlog(self,x):                            
        self.window2 = QtWidgets.QMainWindow()
        self.ui = adminlog.Ui_Form()
        self.ui.setupUi(self.window2)
        self.window2.show()
        x.close()

    def passage2(self):
        self.adminlog(x)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
