# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import sys

import studentas
import studentci
import studentlog
import myinfostudent
import studentpl

check = True


class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(726, 549)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        Form.setInputMethodHints(QtCore.Qt.ImhNone)
        self.s1widget = QtWidgets.QWidget(Form)
        self.s1widget.setGeometry(QtCore.QRect(50, 50, 581, 381))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.s1widget.setFont(font)
        self.s1widget.setStyleSheet("")
        self.s1widget.setObjectName("s1widget")
        self.s1label = QtWidgets.QLabel(self.s1widget)
        self.s1label.setGeometry(QtCore.QRect(69, 40, 491, 321))
        self.s1label.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius:50px")
        self.s1label.setText("")
        self.s1label.setObjectName("s1label")
        self.s1label_2 = QtWidgets.QLabel(self.s1widget)
        self.s1label_2.setGeometry(QtCore.QRect(49, 25, 211, 71))
        self.s1label_2.setStyleSheet("border-top-left-radius:50px;\n"
"background-color:rgba(0,0,0,80);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));")
        self.s1label_2.setText("")
        self.s1label_2.setObjectName("s1label_2")
        self.s1label_5 = QtWidgets.QLabel(self.s1widget)
        self.s1label_5.setGeometry(QtCore.QRect(80, 40, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.s1label_5.setFont(font)
        self.s1label_5.setStyleSheet("color:rgba(255,255,255,220);")
        self.s1label_5.setObjectName("s1label_5")
        self.s1label_6 = QtWidgets.QLabel(self.s1widget)
        self.s1label_6.setGeometry(QtCore.QRect(270, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.s1label_6.setFont(font)
        self.s1label_6.setStyleSheet("color:rgba(0,0,0,200);")
        self.s1label_6.setObjectName("s1label_6")
        self.smyinfo = QtWidgets.QPushButton(self.s1widget)
        self.smyinfo.setGeometry(QtCore.QRect(130, 180, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.smyinfo.setFont(font)
        self.smyinfo.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}")
        self.smyinfo.setObjectName("smyinfo")
        self.s1logout = QtWidgets.QPushButton(self.s1widget)
        self.s1logout.setGeometry(QtCore.QRect(470, 50, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.s1logout.setFont(font)
        self.s1logout.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}")
        self.s1logout.setObjectName("s1logout")
        self.scollegeinfo = QtWidgets.QPushButton(self.s1widget)
        self.scollegeinfo.setGeometry(QtCore.QRect(270, 180, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.scollegeinfo.setFont(font)
        self.scollegeinfo.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}")
        self.scollegeinfo.setObjectName("scollegeinfo")

        self.final = QtWidgets.QPushButton(self.s1widget)
        self.final.setGeometry(QtCore.QRect(270, 290, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.final.setFont(font)
        self.final.setStyleSheet("QPushButton{\n"
                                        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
                                        "    color:rgba(255,255,255,210);\n"
                                        "    border-radius:5px;\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "    padding-left:5px;\n"
                                        "    padding-top:5px;\n"
                                        "    background-color:rgba(150,123,111,255);\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
                                        "}")
        self.final.setObjectName("final")

        self.scollegepref = QtWidgets.QPushButton(self.s1widget)
        self.scollegepref.setGeometry(QtCore.QRect(410, 180, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.scollegepref.setFont(font)
        self.scollegepref.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}")
        self.scollegepref.setObjectName("scollegepref")
        self.s1label_7 = QtWidgets.QLabel(self.s1widget)
        self.s1label_7.setGeometry(QtCore.QRect(130, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.s1label_7.setFont(font)
        self.s1label_7.setStyleSheet("color:rgba(0,0,0,200);")
        self.s1label_7.setObjectName("s1label_7")
        self.s1label_8 = QtWidgets.QLabel(self.s1widget)
        self.s1label_8.setGeometry(QtCore.QRect(270, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.s1label_8.setFont(font)
        self.s1label_8.setStyleSheet("color:rgba(0,0,0,200);")
        self.s1label_8.setObjectName("s1label_8")
        self.s1label_9 = QtWidgets.QLabel(self.s1widget)
        self.s1label_9.setGeometry(QtCore.QRect(410, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.s1label_9.setFont(font)
        self.s1label_9.setStyleSheet("color:rgba(0,0,0,200);")
        self.s1label_9.setObjectName("s1label_9")
        self.s1label_10 = QtWidgets.QLabel(self.s1widget)
        self.s1label_10.setGeometry(QtCore.QRect(270, 255, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.s1label_10.setFont(font)
        self.s1label_10.setStyleSheet("color:rgba(0,0,0,200);")
        self.s1label_10.setObjectName("s1label_10")
        self.s1logout.clicked.connect(self.passage12)
        self.smyinfo.clicked.connect(self.passage)
        self.scollegepref.clicked.connect(self.passage3)
        self.scollegeinfo.clicked.connect(self.passage1)
        self.final.clicked.connect(self.passage2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.s1label_5.setText(_translate("Form", "Student"))
        self.s1label_6.setText(_translate("Form", "Home"))
        self.smyinfo.setText(_translate("Form", "My\n"
"Information"))
        self.s1logout.setText(_translate("Form", "Log Out"))
        self.scollegeinfo.setText(_translate("Form", "College\n"
"Information"))
        self.final.setText(_translate("Form", "Final Allotment\n"
                                                     "Status"))
        self.scollegepref.setText(_translate("Form", "College\n"
"Preference\n"
"List"))
        self.s1label_7.setText(_translate("Form", "Step-1"))
        self.s1label_8.setText(_translate("Form", "Step-2"))
        self.s1label_9.setText(_translate("Form", "Step-3"))
        self.s1label_10.setText(_translate("Form", "Step-4"))

        global check
        check = True
        if(check):
                global x
                x = Form
                check = False

    def studentlog(self,x):                            
        self.window3 = QtWidgets.QMainWindow()
        self.ui = studentlog.Ui_Form()
        self.ui.setupUi(self.window3)
        self.window3.show()
        x.close()

    def passage12(self):
        self.studentlog(x)

    def studentci(self,x):
        self.window3 = QtWidgets.QMainWindow()
        self.ui = studentci.Ui_Form()
        self.ui.setupUi(self.window3)
        self.window3.show()
        x.close()

    def passage1(self):
        self.studentci(x)

    def myinfostudent(self,x):
        self.window = QtWidgets.QMainWindow()
        self.ui = myinfostudent.Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()
        x.close()

    def passage(self):
        self.myinfostudent(x)

    def studentpl(self, x):
        self.window1 = QtWidgets.QMainWindow()
        self.ui =studentpl.Ui_Form()
        self.ui.setupUi(self.window1)
        self.window1.show()
        x.close()

    def passage3(self):
        self.studentpl(x)

    def studentas(self,x):
        self.window2 = QtWidgets.QMainWindow()
        self.ui = studentas.Ui_Form()
        self.ui.setupUi(self.window2)
        self.window2.show()
        x.close()

    def passage2(self):
        self.studentas(x)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
